# 基础镜像
FROM redis
# author
MAINTAINER witos

# 挂载目录
VOLUME /home/witos/redis
# 创建目录
RUN mkdir -p /home/witos/redis
# 指定路径
WORKDIR /home/witos/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/witos/redis/redis.conf
