# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER witos

# 挂载目录
VOLUME /home/witos
# 创建目录
RUN mkdir -p /home/witos
# 指定路径
WORKDIR /home/witos
# 复制jar文件到路径
COPY ./jar/witos-demo.jar /home/witos/witos-demo.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","witos-demo.jar"]
