<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.witos</groupId>
        <artifactId>vpp</artifactId>
        <version>1.2.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>vpp-common-log</module>
        <module>vpp-common-core</module>
        <module>vpp-common-redis</module>
        <module>vpp-common-seata</module>
        <module>vpp-common-swagger</module>
        <module>vpp-common-security</module>
        <module>vpp-common-datascope</module>
		<module>vpp-common-datasource</module>
        <module>vpp-common-mybatisplus</module>
        <module>vpp-common-message</module>
    </modules>

    <artifactId>vpp-common</artifactId>
    <packaging>pom</packaging>

    <description>
	    vpp-common通用模块
    </description>

</project>
